mysite/carts/urls.py
from django.urls import path
from . import views

app_name= 'carts'

urlpatterns =[
    path('',views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar',views.remove, name='remove'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

from django.conf.urls.static import static
from django.conf import settings

from products.views import ProductListView

urlpatterns = [

    path('',ProductListView.as_view(), name='index'),#se hace utiliza una clase como vista
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),# le indicamos adjango que podemos hacer uso de todas las rutas de
    #nuestro producto mediante el prefijo product = productos/:id
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('codigos/', include('promo_codes.urls')),

]

#esto nos permite mostrar la imagen en el template, hace uso de las contantes en settings MEDIA_URL,MEDIA_ROOT
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/orders/urls.py
from django.urls import path

from . import views

app_name ='orders'

urlpatterns = [
    path('',views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address,name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('completados', views.OrderListView.as_view(), name='completeds')

]

mysite/promo_codes/urls.py
from django.urls import path

from . import views

app_name = 'promo_codes'

urlpatterns = [
    path('validar', views.validate, name='validate')
]

mysite/shipping_addresses/urls.py
from django.urls import path

from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddresListView.as_view(), name='shipping_addresses'),
    path('nuevo',views.create, name='create'),
    path('editar/<int:pk>',views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default')

]

mysite/orders/models.py
import uuid
import decimal
from django.db import models

from users.models import User
from carts.models import Cart

from .common import OrderStatus
from .common import choices

from promo_codes.models import PromoCode

from django.db.models.signals import pre_save

from shipping_addresses.models import ShippingAddress


class Order(models.Model):
    order_id = models.CharField(max_length=100, unique=True, null=False, blank=False)
    user=models.ForeignKey(User,on_delete=models.CASCADE) # 1 user puede tener muchas ordenes de ccompra / para generar una roden debe estar un usuario
    cart =models.ForeignKey(Cart,on_delete=models.CASCADE) # 1 carrito-> muchas ordenes / una orden puede tener varios estatus
    status = models.CharField(max_length=50, choices=choices,# se convierte en un menu
                              default=OrderStatus.CREATED) #Enum
    shipping_total = models.DecimalField(default=5,max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0,max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    shipping_address = models.ForeignKey(ShippingAddress,null=True,blank=True,on_delete=models.CASCADE)
    promo_code = models.ForeignKey(PromoCode, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.order_id

    def apply_promo_code(self, promo_code):
        if self.promo_code is None:
            self.promo_code = promo_code
            self.save()

            self.update_total()
            promo_code.use()

    def get_ot_set_shipping_address(self):
        if self.shipping_address: # obtenemos la direccion de envio que tiene la orden
            return self.shipping_address
        shipping_address = self.user.shipping_address #Buscamos traes la del usuario
        if shipping_address: #actualizamos la orden con es direccion
           self.update_shipping_address(shipping_address)
        return shipping_address

    def update_shipping_address(self, shipping_address ):
        self.shipping_address = shipping_address
        self.save()

    def cancel(self):
        self.status = OrderStatus.CANCELED
        self.save()

    def complete(self):
        self.status = OrderStatus.COMPLETED
        self.save()


    def update_total(self):
        self.total = self.get_total()
        self.save()

    def get_discount(self):
        if self.promo_code:
            return self.promo_code.discount

        return 0

    def get_total(self):
        return self.cart.total + self.shipping_total - decimal.Decimal( self.get_discount())

def set_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())

def set_total(sender, instance, *args, **kwargs):
    instance.total = instance.get_total()

pre_save.connect(set_order_id, sender=Order)
pre_save.connect(set_total, sender=Order)#antes que un objeto de tipo order se guarde, se ejecutara el callback set_total

mysite/orders/views.py
import threading

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import render, get_object_or_404, redirect

from carts.utils import get_or_create_cart
from carts.utils import destroy_cart
from .models import Order

from .utils import get_or_create_order
from .utils import breadcrumb
from .utils import destroy_order

from .mails import Mail

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic.list import ListView
from django.db.models.query import EmptyQuerySet

from shipping_addresses.models import ShippingAddress


class OrderListView(LoginRequiredMixin, ListView):
    login_url = 'login'
    template_name='orders/orders.html'

    def get_queryset(self):
        return self.request.user.orders_completed()


@login_required(login_url='login') #se restringe vista para user autenticado
def order(request):
    cart = get_or_create_cart(request)
    order =get_or_create_order(cart,request)

    return render(request, 'orders/order.html',{
        'cart':cart,
        'order':order,
        'breadcrumb':breadcrumb()
    })

@login_required(login_url='login')
def address(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart,request)
    shipping_address = order.get_ot_set_shipping_address()
    can_choose_address =request.user.has_shipping_addresses()

    return  render(request, 'orders/address.html',{
        'cart':cart,
        'order':order,
        'shipping_address' : shipping_address,
        'can_choose_address' : can_choose_address,
        'breadcrumb':breadcrumb(address=True)
    })
@login_required(login_url='login')
def select_address(request):#Nota: se movieron las consultas dentro del modelo (método, propiedad)
    shipping_addresses = request.user.addresses#obtenemos todas la direcciones
    return  render(request, 'orders/select_address.html',{
        'breadcrumb':breadcrumb(address=True),
        'shipping_addresses':shipping_addresses

    })
@login_required(login_url='login')
def check_address(request, pk):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart,request)

    shipping_address = get_object_or_404(ShippingAddress,pk=pk)

    if request.user.id != shipping_address.user_id:
        return redirect('carts:cart')
    order.update_shipping_address(shipping_address)

    return redirect('orders:address')

@login_required(login_url='login')
def confirm(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)

    shipping_address = order.shipping_address
    if shipping_address is None:
        return redirect('orders:address')

    return render(request, 'orders/confirm.html',{
        'cart':cart,
        'order': order,
        'shipping_address':shipping_address,
        'breadcrumb': breadcrumb(address=True, confirmation=True)
    })

@login_required(login_url='login')
def cancel(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)

    #seguridad
    if request.user.id != order.user.id: # en caso de no ser el usuario que creo la orden lo mandamos a otra vista
        return redirect('carts:cart')

    order.cancel()

    destroy_order(request)
    destroy_cart(request)


    messages.error(request, 'Orden cancelada')
    return redirect('index')

@login_required(login_url='login')
def complete(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)

    # seguridad
    if request.user.id != order.user_id:  # en caso de no ser el usuario que creo la orden lo mandamos a otra vista
        return redirect('carts:cart')

    order.complete()
    #Se envia el correo de manera asincrona mediante un hilo
    thread =threading.Thread(target=Mail.send_complete_order,args=(
        order, request.user
    ))
    thread.start()



    destroy_order(request)
    destroy_cart(request)

    messages.success(request, 'Compra completada exitosamente')
    return redirect('index')

mysite/orders/templates/orders/address.html
{% extends 'base.html' %}
{% block breadcrumb %}
  {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
  <div class="col">
    {% if shipping_address %}
      <div class="h3">
        Recoge el pedido en el punto de entrega
      </div>
    <div class="">
      {% include 'shipping_addresses/snippets/shipping_address.html' %}

      <div class="mt-2">
        <a href="{% url 'orders:confirm' %}" class="btn btn-warning">Entregar a esta dirección</a>
      </div>

      {% if can_choose_address %}
        <div class="mt-2">
          <a href="{% url 'orders:select_address' %}">Otra dirección</a>
        </div>
      {% endif %}


    </div>
    {% else %}
      <div class="h3">
        Registra tu dirección de envío
      </div>
    <div class="">
      {% url 'orders:address' as next_url %}
      <a href="{% url 'shipping_addresses:create' %}?next={{ next_url }}">Nueva dirección de envío</a>
    </div>
    {% endif %}
  </div>
{% endblock %}

mysite/orders/templates/orders/confirm.html
{% extends 'base.html' %}

{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
    <div class="col-8">
        <div class="h3">
            Confirma tú pedido
        </div>
        <div class="card">
            <dic class="card-body">
                <div class="row">

                    <div class="col-4">
                        <div class="font-weight-bold">
                            Dirección de envío
                        </div>
                        <div class="cart-text">
                            {{ shipping_address.city }}
                        </div>
                        <div class="cart-text">
                            {{ shipping_address.line1 }}
                        </div>
                        <div class="cart-text">
                            {{ shipping_address.line2 }}
                        </div>
                        <div class="card-text">
                            {{ shipping_address.reference }}
                        </div>
                        <div class="cart-text">
                            {{ shipping_address.postal_code }}
                        </div>

                    </div>

                    <div class="col-4">
                        <div class="font-weight-bold">
                            Método de pago
                        </div>
                        <div class="card-text">
                            Tarjeta terminacion 4242
                        </div>

                    </div>

                    <div class="col-4">
                        <div class="font-weight-bold">
                            Código promocional
                        </div>
                        <form id="promocode-form" action="{% url 'promo_codes:validate' %}">
                            <input type="text" name="code" value="{{ order.promo_code.code }}" class="form-control" placeholder="código promoción" {% if order.promo_code %} readonly {%endif%} >
                        </form>
                        <div class="text-success" id="promocode-success" style="font-size:14px">
                            {% if order.promo_code %}
                            Código aplicado exitosamente
                            {% endif %}

                        </div>

                    </div>

                </div>

            </dic>

        </div>

        <div class="mt-3">
            <div class="card">
                <div class="card">
                    <div class="card-body">
                        {% for product in cart.products.all %}
                            {% include 'orders/snippets/product.html' %}
                        {% endfor %}

                    </div>

                </div>

            </div>

        </div>

    </div>

    <div class="col">
        {% url 'orders:complete' as next_url %}
        {% include 'orders/snippets/resume.html' with next_utl=next_url %}
        <div class="mt-2">

            <a href="{% url 'orders:cancel' %}" class="btn btn-danger">Cancelar orden</a>
        </div>

    </div>
{% endblock %}

{% block javascript %}

    <script >
        const form = document.getElementById('promocode-form')
        form.addEventListener('submit',function(e){
            e.preventDefault()

            const input =this.code
            const code = input.value
            const url = this.action + "?code=" + code
            const div_total = document.getElementById('order-total')
            const div_success = document.getElementById('promocode-success')

            console.log(url)

            fetch(url)//trabajamos con promesas
                .then(response => response.json())//convertimos a json
                .then(response => {
                    console.log(response.total)

                    if(response.status === true){
                        div_total.innerHTML="$" + response.total
                        div_success.classList.remove('text-danger')
                        div_success.classList.add('text-success')
                        div_success.innerHTML='Código aplicado exitosamente'
                        input.readOnly = true

                    }else{
                        div_success.innerHTML='Código no valido'
                        div_success.classList.remove('text-success')
                        div_success.classList.add('text-danger')


                    }
                })

        })
    </script>

{% endblock %}

mysite/orders/templates/orders/order.html
{% extends 'base.html' %}
{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}



{% block content %}

    <div class="col-8">
        <div class="h3">
            Revisa tú pedido
        </div>
        <div class="card">
            <div class="card-body">
                {% for product in cart.products.all %}
                    {% include 'orders/snippets/product.html' %}

                {% endfor %}
            </div>
        </div>
    </div>
    <div class="col">
        {% url 'orders:address' as next_url %}
        {% include 'orders/snippets/resume.html' with next_url=next_url %}
    </div>

{% endblock %}

mysite/orders/templates/orders/orders.html
{% extends 'base.html' %}
{% block content %}
  <div class="col">
    <div class="h3">
      Mis pedidos
    </div>
    <div class="">
      {% for order in object_list %}
        {% include 'orders/snippets/order.html'%}
      {% endfor %}
    </div>

  </div>
{% endblock %}

mysite/orders/templates/orders/select_address.html
{% extends 'base.html' %}

{% block breadcrumb %}
  {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
  <dvi class="col">
    <div class="h3">
      Selecciona una dirección de envío
    </div>
    <div class="mt-2">
      {% for shipping_address in shipping_addresses %}
        <div class="card mb-2">
          <div class="card-body">
            <h5 class="card-title">{{ shipping_address.address }}</h5>
            <p class="card-title">{{ shipping_address.postal_code }}</p>
            <a href="{% url 'orders:check_address' shipping_address.pk %}" class="btn btn-warning">Seleccionar</a>

          </div>
        </div>
      {% endfor %}
    </div>

  </dvi>


{% endblock %}