mysite/carts/urls.py
from django.urls import path
from . import views

app_name= 'carts'

urlpatterns =[
    path('',views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar',views.remove, name='remove'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

from django.conf.urls.static import static
from django.conf import settings

from products.views import ProductListView

urlpatterns = [

    path('',ProductListView.as_view(), name='index'),#se hace utiliza una clase como vista
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),# le indicamos adjango que podemos hacer uso de todas las rutas de
    #nuestro producto mediante el prefijo product = productos/:id
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('codigos/', include('promo_codes.urls')),

]

#esto nos permite mostrar la imagen en el template, hace uso de las contantes en settings MEDIA_URL,MEDIA_ROOT
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/orders/urls.py
from django.urls import path

from . import views

app_name ='orders'

urlpatterns = [
    path('',views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address,name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('completados', views.OrderListView.as_view(), name='completeds')

]

mysite/shipping_addresses/urls.py
from django.urls import path

from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddresListView.as_view(), name='shipping_addresses'),
    path('nuevo',views.create, name='create'),
    path('editar/<int:pk>',views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default')

]

mysite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>Title</title>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>

{% include 'navbar.html' %}
<div class="container">

    {% include 'message.html'%}

    {% block breadcrumb %}
    {% endblock %}

  <div class="row mt-3">

    {% block content %}
    {% endblock %}

  </div>
</div>

</body>
<script src="https://kit.fontawesome.com/92a30b6d2f.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

{% block javascript %}
{% endblock %}

</html>

mysite/templates/index.html
{% extends 'base.html' %}

    {% block content %}

        <div class="col">
                <h4 class="text-center">{{message}}</h4>
            {% include 'products/snippets/search.html' %}

            {% include 'products/snippets/list.html' %}
        </div>

    {% endblock %}

mysite/templates/message.html
  {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags == 'success' %} alert-success alert-dismissible fade show {% else %} alert alert-danger alert-dismissible fade show {% endif %}">
               <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
              {{message}}
            </div>

        {% endfor %}
     {% endif %}

mysite/templates/navbar.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'carts:cart' as cart %}
{% url 'shipping_addresses:shipping_addresses' as shipping_addresses %}
{% url 'orders:completeds' as completeds %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a href="{% url 'index' %}" class="navbar-brand">Store</a>

      <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navb">
          <span class="navbar-toggler-icon"></span>
      </button>



  <div id="navb" class="navbar-collapse collapse hide">

      <ul class="navbar-nav">
          <li class="nav-item {% if request.path == cart %}active {%endif%}" >
              <a class="nav-link"  href="{{ cart }}">
                  Mi carrito <span class="fas fa-shopping-cart" ></span>
              </a>
          </li>
          {% if user.is_authenticated %}
           <li class="nav-item {% if request.path == shipping_addresses %}active {%endif%}" >
              <a class="nav-link"  href="{{ shipping_addresses }}">
                  Mis direcciones <span class="fas fa-location-arrow" ></span>
              </a>
          </li>

          <li class="nav-item {% if request.path == completeds %}active {%endif%}" >
              <a class="nav-link"  href="{{ completeds }}">
                  Mis pedidos <span class="fas fa-shipping-fast" ></span>
              </a>
          </li>
          {% endif %}
      </ul>



    <ul class="nav navbar-nav ml-auto">
        {% if user.is_authenticated %}
            <li class="navbar-item  ">
            <a href="{% url 'logout' %}" class="nav-link"><span class="fas fa-sign-in-alt"></span>Logout</a>

            </li>
        {% else %}

          <li class="navbar-item {% if request.path == login %}active{%endif%}">
            <a href="{% url 'login' %}" class="nav-link"><span class="fas fa-user"></span>Login</a>

          </li>

             <li class="navbar-item {% if request.path == register %}active{%endif%} ">
            <a href="{% url 'register'%}" class="nav-link"><span class="fas fa-user-plus"></span>Registro</a>

          </li>
        {%endif%}


    </ul>



  </div>

</nav>